version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - CONSUMER_KEY=CONSUMER_KEY_VALUE
      - CONSUMER_SECRET=CONSUMER_SECRET_VALUE
      - ACCESS_TOKEN_KEY=ACCESS_TOKEN_KEY_VALUE
      - ACCESS_TOKEN_SECRET=ACCESS_TOKEN_SECRET_VALUE
